version: '3.7'
services:
  mongodb:
    container_name: "mongo"
    image: mongo:4.2.21-bionic
    environment:
      MONGO_INITDB_PASSWORD: root
      MONGO_INITDB_USERNAME: root
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  mongo-express:
    container_name: "mongo-express"
    image: mongo-express:latest
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://mongodb:27017"
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: True
      ME_CONFIG_MONGODB_AUTH_DATABASE: "admin"
      ME_CONFIG_MONGODB_AUTH_USERNAME: "root"
      ME_CONFIG_MONGODB_AUTH_PASSWORD: "root"
      ME_CONFIG_BASICAUTH_USERNAME: "test"
      ME_CONFIG_BASICAUTH_PASSWORD: "test"

    ports:
      - 8081:8081
    volumes:
      - mongodb_data_container:/data/db 

volumes:
  mongodb_data_container: